<?php

/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Mage
 * @package    Mage_BankPayment
 * @copyright  Copyright (c) 2008 Andrej Sinicyn
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

?>
<fieldset class="form-list">
    <ul id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none">
        <li>
            <div class="input-box">
                <?php if ($this->getMethod()->getPayWithinXDays() > 0): ?>
                    <?php echo $this->__('Please transfer the money within %s days to the following bank account', $this->getMethod()->getPayWithinXDays()); ?>:
                <?php else: ?>
                    <?php echo $this->__('Please transfer the money to the following bank account'); ?>:
                <?php endif; ?><br /><br />
                <?php if ($this->getMethod()->getAccountHolder()): ?>
                    <?php echo '<label>'.$this->__('Account holder').'</label>: '.$this->getMethod()->getAccountHolder() ?><br />
                <?php endif; ?>
                <?php if ($this->getMethod()->getAccountNumber()): ?>
                    <?php echo '<label>'.$this->__('Account number').'</label>: '.$this->getMethod()->getAccountNumber() ?><br />
                <?php endif; ?>
                <?php if ($this->getMethod()->getSortCode()): ?>
                    <?php echo '<label>'.$this->__('Sort code').'</label>: '.$this->getMethod()->getSortCode() ?><br />
                <?php endif; ?>
                <?php if ($this->getMethod()->getBankName()): ?>
                    <?php echo '<label>'.$this->__('Bank name').'</label>: '.$this->getMethod()->getBankName() ?><br />
                <?php endif; ?>
                <?php if ($this->getMethod()->getIBAN() && $this->getMethod()->getBIC()): ?>
                    <br /><br />
                    <?php echo $this->__('For international transfers please use also following data') ?>:<br /><br />
                    <?php echo '<label>'.$this->__('IBAN').'</label>: '.$this->getMethod()->getIBAN() ?><br />
                    <?php echo '<label>'.$this->__('BIC').'</label>: '.$this->getMethod()->getBIC() ?><br />
                <?php endif; ?>
                <?php if ($this->getMethod()->getCustomText()): ?>
                    <br />
                    <?php echo $this->getMethod()->getCustomText() ?><br />
                <?php endif; ?>
            </div>
        </li>
    </ul>
</fieldset>
