<?php

/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Mage
 * @package    Mage_BankPayment
 * @copyright  Copyright (c) 2008 Andrej Sinicyn
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

?>
<p>
    <?php echo $this->getMethod()->getTitle() ?><br />
    <div style="font-style: italic"><?php echo $this->__('Account info'); ?></div>
    <?php if ($this->getMethod()->getAccountHolder()): ?>
        <?php echo '<label>'.$this->__('Account holder').'</label>: '.$this->getMethod()->getAccountHolder() ?><br />
    <?php endif; ?>
    <?php if ($this->getMethod()->getAccountNumber()): ?>
        <?php echo '<label>'.$this->__('Account number').'</label>: '.$this->getMethod()->getAccountNumber() ?><br />
    <?php endif; ?>
    <?php if ($this->getMethod()->getSortCode()): ?>
        <?php echo '<label>'.$this->__('Sort code').'</label>: '.$this->getMethod()->getSortCode() ?><br />
    <?php endif; ?>
    <?php if ($this->getMethod()->getBankName()): ?>
        <?php echo '<label>'.$this->__('Bank name').'</label>: '.$this->getMethod()->getBankName() ?><br />
    <?php endif; ?>
    <?php if ($this->getMethod()->getIBAN() && $this->getMethod()->getBIC()): ?>
        <br />
        <div style="font-style: italic"><?php echo $this->__('International') ?></div>
        <?php echo '<label>'.$this->__('IBAN').'</label>: '.$this->getMethod()->getIBAN() ?><br />
        <?php echo '<label>'.$this->__('BIC').'</label>: '.$this->getMethod()->getBIC() ?><br />
    <?php endif; ?>
    <?php if ($this->getMethod()->getCustomText()): ?>
        <br />
        <?php echo $this->getMethod()->getCustomText() ?><br />
    <?php endif; ?>
</p>
